import { appPool } from "../index";

export const createEnrolTable = async function (): Promise<void> {
	//imageFileName is dynamic and generated by merging phoneNumber
	//with imageFile file type e.g png,jpg i.e imageFileName=phoneNumber.jpg/png

	const createSQLTable: string = `CREATE TABLE IF NOT EXISTS enrolment_Table (
    id 
        INT PRIMARY KEY AUTO_INCREMENT,
    course 
        VARCHAR(100) NOT NULL,
    fullName 
        VARCHAR(255) NOT NULL,
    imageFileHash
        VARCHAR(255) NOT NULL,
    imageFileName 
        VARCHAR(255) NOT NULL COMMENT 'imageFileName is dynamic and generated by merging phoneNumber with imageFile file type e.g png,jpg i.e imageFileName=phoneNumber.jpg/png' ,
    imageFile 
        LONGBLOB NOT NULL COMMENT 'THE IMAGE FILE itself IN BUFFER/BLOB',
    imageFileExtType
        VARCHAR(100) COMMENT 'is the image File an jpeg,png,etc',
    phoneNumber 
        VARCHAR(20) NOT NULL UNIQUE,
    registration_status 
        ENUM('PROCESSING','ERROR','COMPLETED') DEFAULT 'PROCESSING',
    registration_message
        VARCHAR(255) DEFAULT NULL COMMENT 'used mostly by updated route',
    createdAt 
        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt 
        TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)`;

	const conn = await appPool.getConnection();

	try {
		await conn.query(createSQLTable);
		console.log("enrolment_table created.");
	} catch (err) {
		console.error("❌ Error creating enrol table:", err);
		throw err;
	} finally {
		conn.release();
	}
};
